### PR TITLE
Search Bar

### PR DESCRIPTION
**Pull request by j8r**
I add a search bar. I ve tried on WebIDE  but there are no files, therefore i don't know if it works well... or not.

### CODE REVIEW

**Comment by FabianOvrWrt** [comment]
Well, i've tested it now and it doesn't work (but you already said that in the modified files).
I can't make it work, so I need to let that to you (I'm not a developer, but a designer).

Do you have a Firefox OS phone? otherwise it would be very difficult for me to test every change that you make. I'm not closing this, looks interesting (specially for the "file picker" option).

There's an app that does file searching right now on the Marketplace, so take a look at it, maybe you find something useful there.
https://github.com/applait/finder

**Comment by j8r** [comment]
I've looked before, but integrate a JQuery plugin is simpler. I've a Firefox OS phone (GP Revolution), but i've problems to connect to my GNU/Linux PC. I'm trying to fix it soon as possible.
I'm not a "dev", but i try to understand how it works and try to integrate/change/improve code.

**Comment by j8r** [comment]
I can do like a "2 in 1" app, with a feature like "advanced search" with applait's finder... But resolve all depedencies like same markers, css, and js is not short :/

**Comment by j8r** [comment]
I've tried to connect my Geeksphone Revolution to my PC, nothing. I've gone to mdn, geeksphone forum but this don't work. I will try in few days in an another PC, it could be done :), i never give up until this is fixed ! Next, i will add an Advanced Search (finder), because this search is only for the actual folder.

**Comment by j8r** [comment]
[File Manager](https://github.com/elfoxero/file-manager) is reborn ! I will work more on my side, it's simple, thanks.

**Pull request closed without merging**
